### ISSUE TITLE
Collaboration conflicts with two people in the same Environment

### ISSUE THREAD

**Issue by bushong1** [USSBA/aws-cft-tools#17]
One issue we have been having lately is when two people are working in the same Environment, there can be conflicts.  Usually these conflicts can be avoided by using the "role" feature.  The problem arises when a change is made to a base layer stack, such as adding a new Export value.  Because the role feature deploys all dependent stacks as well as the role-specific stacks, adding an Export to the VPC (for example), can be exceedingly difficult to time.

One solution to this problem would be to add a feature that takes the role based deployment and *only* deploys the stacks tagged with that specific role name.  Any thoughts?

**Comment by jgsmith-usds** [comment]
This might be related to #16 .

**Comment by bushong1** [comment]
Closing in favor of #16
