### ISSUE TITLE
Rate Limiting with `-j 3`

### ISSUE THREAD

**Issue by bushong1** [USSBA/aws-cft-tools#33]
When i run with `-j 3` to allow 3 concurrent jobs, I typically hit an AWS Rate Limiting barrier:

```
.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.9.44/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Rate exceeded (Aws::CloudFormation::Errors::Throttling)
```

I'm curious if it's possible to self-limit or backoff/retry in the case of a Throttling error.

**Comment by jgsmith-usds** [comment]
Had a similar thought. I'll be spending some time next week on aws-cft-tools stuff.
